### ISSUE TITLE
Error parsing glade file

### ISSUE THREAD

**Issue by GrbavaCigla** [welbornprod/glader#2]
```
Error parsing glade file!: PiTV/sidebar.glade
'NoneType' object has no attribute 'name'

No usable info was found for this file: PiTV/sidebar.glade
```

**Comment by cjwelborn** [comment]
Can you post the glade file somewhere so I can look at it (a pastebin or something)?

**Comment by GrbavaCigla** [comment]
https://www.github.com/PiSmartTV/PiTV
In folder PiTV, application.glade

**Comment by cjwelborn** [comment]
Thanks, I have to get back home before I can look into it (a few hours), but I'll get back to you. I'm interested in seeing what has changed/broken.

**Comment by cjwelborn** [comment]
So I found a little bug in Glader, where it wasn't handling elements without an `id`. I can generate code for your glade file, but it doesn't produce correct results because there is more than one main window.

Glader assumes that you will have one main GtkWindow per file (you generate Python code for the separate files with (using `--lib` on one of them) and just combine them by importing the classes). That's something I want to fix. I'm gonna make this my next little project.

Here's what Glader will generate at the moment, notice there's three `destroy()` handlers because Glader doesn't realize they are for a different window/object. That's the part I want to fix:
```python
class App(Gtk.Window):
    """ Main window with all components. """

    def __init__(self):
        Gtk.Window.__init__(self)
        self.builder = Gtk.Builder()
        gladefile = '/home/cj/dump/test.glade'
        if not os.path.exists(gladefile):
            # Look for glade file in this project's directory.
            gladefile = os.path.join(sys.path[0], gladefile)

        try:
            self.builder.add_from_file(gladefile)
        except Exception as ex:
            print('\nError building main window!\n{}'.format(ex))
            sys.exit(1)

        # Get gui objects
        self.home_stack_list = self.builder.get_object('home_stack_list')
        self.home_window = self.builder.get_object('home_window')
        self.login_box = self.builder.get_object('login_box')
        self.login_error_label = self.builder.get_object('login_error_label')
        self.login_password_field = self.builder.get_object('login_password_field')
        self.login_spinner = self.builder.get_object('login_spinner')
        self.login_stack = self.builder.get_object('login_stack')
        self.login_username_field = self.builder.get_object('login_username_field')
        self.login_window = self.builder.get_object('login_window')
        self.main_divider = self.builder.get_object('main_divider')
        self.main_stack = self.builder.get_object('main_stack')
        self.sidebar = self.builder.get_object('sidebar')
        self.sidebar_actions_list = self.builder.get_object('sidebar_actions_list')
        self.signup_box = self.builder.get_object('signup_box')
        self.signup_email_field = self.builder.get_object('signup_email_field')
        self.signup_error_label = self.builder.get_object('signup_error_label')
        self.signup_name_field = self.builder.get_object('signup_name_field')
        self.signup_password_field = self.builder.get_object('signup_password_field')
        self.signup_retype_password_field = self.builder.get_object('signup_retype_password_field')
        self.signup_spinner = self.builder.get_object('signup_spinner')
        self.signup_username_field = self.builder.get_object('signup_username_field')
        self.weather_image = self.builder.get_object('weather_image')
        self.weather_label = self.builder.get_object('weather_label')

        # Connect all signals.
        self.builder.connect_signals(self)

        # Show the main window.
        self.home_window.show_all()

    def destroy(self, widget, user_data=None):
        """ Handler for destroy.destroy. """
        pass

    def destroy(self, widget, user_data=None):
        """ Handler for destroy.destroy. """
        pass

    def destroy(self, widget, user_data=None):
        """ Handler for destroy.destroy. """
        pass

    def on_sidebar_row_selected(self, widget, row, user_data=None):
        """ Handler for on.row-selected. """
        pass
```

I'll probably work on it this weekend.

**Comment by GrbavaCigla** [comment]
Excellent, Thanks!
So do I close this issue?

**Comment by cjwelborn** [comment]
@GrbavaCigla, Glader is able to generate working code for your glade file now. It was a little tricky connecting up all of the signals, so it's not perfect. Glader was always meant to be a "starting point" anyway. It's just a way to get the skeleton written so you can start editing and adding functionality. As a side note, I noticed your glade file uses regular function names, and sometimes uses the same handler for more than one widget. Usually, all widgets have a handler that starts with their name (like `login_window_destroy` instead of `destroy`). It helps you keep track of everything when there are a lot of signals. You can still re-use code, you just have those handlers call a common function. Glade will actually help you with this when you're naming the signal handler. If you start typing the widget name, it will automatically suggest '<widget_name>_signal_name`.

Anyway, it's a starting point. With the current code generation, you have to do things like `self.winLogin.winLogin` if you're using a child window from the main application window. It gives you access to the class that is generated, and the actual Gtk object. Both are useful. All your glade file needs now is some more code to start actually "doing things". :)

I would've closed this issue at this point, but you've already done that. Please file another one if anything pops up. Thank you for the help.

**Comment by GrbavaCigla** [comment]
Hi, me again. I tested glader again on another simpler example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated with glade 3.22.2 -->
<interface>
  <requires lib="gtk+" version="3.20"/>
  <template class="ListTile" parent="GtkBox">
    <property name="visible">True</property>
    <property name="can_focus">False</property>
    <child>
      <object class="GtkLabel">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="halign">start</property>
        <property name="label" translatable="yes">UNKNOWN</property>
        <attributes>
          <attribute name="weight" value="bold"/>
          <attribute name="scale" value="1.5"/>
        </attributes>
      </object>
      <packing>
        <property name="expand">True</property>
        <property name="fill">True</property>
        <property name="padding">6</property>
        <property name="position">0</property>
      </packing>
    </child>
    <child>
      <object class="GtkImage">
        <property name="visible">True</property>
        <property name="can_focus">False</property>
        <property name="margin_left">87</property>
        <property name="pixel_size">48</property>
        <property name="icon_name">accessories-calculator</property>
      </object>
      <packing>
        <property name="expand">False</property>
        <property name="fill">True</property>
        <property name="position">1</property>
      </packing>
    </child>
  </template>
</interface>
```
And this gives me this error:
```
Traceback (most recent call last):
  File "/usr/local/share/glader/glader_ui.py", line 157, in btnGenerate_clicked_cb
    return self.generate_code()
  File "/usr/local/share/glader/glader_ui.py", line 240, in generate_code
    content = gladefile.get_content(lib_mode=lib_mode)
  File "/usr/local/share/glader/glader_util.py", line 153, in get_content
    self.app_win.get_class_content(
  File "/usr/local/share/glader/glader_util.py", line 624, in get_class_content
    widget=self.widget.replace('Gtk', ''),
AttributeError: 'NoneType' object has no attribute 'replace'
```
And when i try to close it:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/glader/glader_ui.py", line 194, in winMain_destroy_cb
    settings.save()
  File "/usr/lib/python3.8/site-packages/easysettings/easy_settings.py", line 685, in save
    raise esSaveError(ex)
easysettings.easy_settings.esSaveError: [Errno 13] Permission denied: '/usr/local/share/glader/glader.conf'
```

**Comment by cjwelborn** [comment]
This is a file-system permissions error. I can make Glader use a config file under the home directory to solve this. In the meantime, if you uninstall Glader and re-install with `./install --user` it will make sure the config file is in a writable directory.  I'll look at it tonight.

**Comment by GrbavaCigla** [comment]
Thanks, but does it solve first error?

**Comment by cjwelborn** [comment]
Glader now uses a config file in `~/.config/glader`, which will be cleaned up if the installer is used to uninstall Glader.

Glader will now issue a warning if there is no top-level window to build. It can't generate code for arbitrary widgets. It needs a top-level window, preferably with some children (because otherwise the window wouldn't do anything).
